// Generated by gencpp from file dsr_msgs/AlignAxis1Request.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_ALIGNAXIS1REQUEST_H
#define DSR_MSGS_MESSAGE_ALIGNAXIS1REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct AlignAxis1Request_
{
  typedef AlignAxis1Request_<ContainerAllocator> Type;

  AlignAxis1Request_()
    : x1()
    , x2()
    , x3()
    , source_vect()
    , axis(0)
    , ref(0)  {
      x1.assign(0.0);

      x2.assign(0.0);

      x3.assign(0.0);

      source_vect.assign(0.0);
  }
  AlignAxis1Request_(const ContainerAllocator& _alloc)
    : x1()
    , x2()
    , x3()
    , source_vect()
    , axis(0)
    , ref(0)  {
  (void)_alloc;
      x1.assign(0.0);

      x2.assign(0.0);

      x3.assign(0.0);

      source_vect.assign(0.0);
  }



   typedef boost::array<double, 6>  _x1_type;
  _x1_type x1;

   typedef boost::array<double, 6>  _x2_type;
  _x2_type x2;

   typedef boost::array<double, 6>  _x3_type;
  _x3_type x3;

   typedef boost::array<double, 3>  _source_vect_type;
  _source_vect_type source_vect;

   typedef int8_t _axis_type;
  _axis_type axis;

   typedef int8_t _ref_type;
  _ref_type ref;





  typedef boost::shared_ptr< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> const> ConstPtr;

}; // struct AlignAxis1Request_

typedef ::dsr_msgs::AlignAxis1Request_<std::allocator<void> > AlignAxis1Request;

typedef boost::shared_ptr< ::dsr_msgs::AlignAxis1Request > AlignAxis1RequestPtr;
typedef boost::shared_ptr< ::dsr_msgs::AlignAxis1Request const> AlignAxis1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator1> & lhs, const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.x2 == rhs.x2 &&
    lhs.x3 == rhs.x3 &&
    lhs.source_vect == rhs.source_vect &&
    lhs.axis == rhs.axis &&
    lhs.ref == rhs.ref;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator1> & lhs, const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b58a6b9aa751aa4ac3b4fa16f7db70aa";
  }

  static const char* value(const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb58a6b9aa751aa4aULL;
  static const uint64_t static_value2 = 0xc3b4fa16f7db70aaULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/AlignAxis1Request";
  }

  static const char* value(const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#____________________________________________________________________________________________\n"
"# align_axis(x1, x2, x3, source_vect, axis, ref)\n"
"#____________________________________________________________________________________________\n"
"\n"
"float64[6] x1                # task pos(posx)  \n"
"float64[6] x2                # task pos(posx)  \n"
"float64[6] x3                # task pos(posx)\n"
"float64[3] source_vect       # source vector[3]  \n"
"int8       axis              # DR_AXIS_X(0), DR_AXIS_Y(1), DR_AXIS_Z(2) \n"
"int8       ref               # DR_BASE(0), DR_WORLD(2), user coord(101~200)\n"
"                             # <ref is only available in M2.40 or later> \n"
;
  }

  static const char* value(const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.x2);
      stream.next(m.x3);
      stream.next(m.source_vect);
      stream.next(m.axis);
      stream.next(m.ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AlignAxis1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::AlignAxis1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::AlignAxis1Request_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x1: ";
    if (v.x1.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.x1.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.x1[i]);
    }
    if (v.x1.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x2: ";
    if (v.x2.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.x2.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.x2[i]);
    }
    if (v.x2.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x3: ";
    if (v.x3.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.x3.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.x3[i]);
    }
    if (v.x3.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source_vect: ";
    if (v.source_vect.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.source_vect.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.source_vect[i]);
    }
    if (v.source_vect.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "axis: ";
    Printer<int8_t>::stream(s, indent + "  ", v.axis);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ref);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_ALIGNAXIS1REQUEST_H
